version: 2

project_name: pocketbase

dist: .builds

before:
  hooks:
    - go mod tidy

builds:
  - id: build_noncgo
    main: ./examples/base
    binary: pocketbase
    ldflags:
      - -s -w -X github.com/pocketbase/pocketbase.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
      - GONOSUMDB=*
      - GOTOOLCHAIN=go1.25.0
      - GOPROXY=https://proxy.golang.org,https://goproxy.cn,https://goproxy.io,direct
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - s390x
      - ppc64le
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: s390x
      - goos: windows
        goarch: ppc64le
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: s390x
      - goos: darwin
        goarch: ppc64le

  - id: build_noncgo_pocket
    main: ./examples/pocket
    binary: pocket
    ldflags:
      - -s -w -X github.com/pocketbase/pocketbase.Version={{ .Version }}
      - -s -w -X "github.com/btwiuse/version.MajorString=0"
      - -s -w -X "github.com/btwiuse/version.MinorString=6"
      - -s -w -X "github.com/btwiuse/version.GitCommitString={{.Commit}}"
      - -s -w -X "github.com/btwiuse/version.GitTreeStateString=clean"
      - -s -w -X "github.com/btwiuse/version.GitVersionString={{.Version}}"
      - -s -w -X "github.com/btwiuse/version.BuildDateString={{.Date}}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm

release:
  draft: false

archives:
  - id: archive_noncgo_pocket
    builds:
      - build_noncgo_pocket
    formats:
      - zip
    files:
      - LICENSE.md
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^examples:'
      - '^ui:'
