project_name: pocketbase

dist: .builds

before:
  hooks:
    - go mod tidy

builds:
  # used only for tests
  - id: build_cgo
    main: ./examples/base
    binary: pocketbase
    ldflags:
      - -s -w -X github.com/pocketbase/pocketbase.Version={{ .Version }}
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64

  - id: build_noncgo
    main: ./examples/base
    binary: pocketbase
    ldflags:
      - -s -w -X github.com/pocketbase/pocketbase.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm

  - id: build_noncgo_pocket
    main: ./examples/pocket
    binary: pocket
    ldflags:
      - -s -w -X github.com/pocketbase/pocketbase.Version={{ .Version }}
      - -s -w -X "github.com/btwiuse/version.MajorString=0"
      - -s -w -X "github.com/btwiuse/version.MinorString=6"
      - -s -w -X "github.com/btwiuse/version.GitCommitString={{.Commit}}"
      - -s -w -X "github.com/btwiuse/version.GitTreeStateString=clean"
      - -s -w -X "github.com/btwiuse/version.GitVersionString={{.Version}}"
      - -s -w -X "github.com/btwiuse/version.BuildDateString={{.Date}}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm

release:
  draft: true

archives:
  - id: archive_noncgo_pocket
    builds:
      - build_noncgo_pocket
    format: zip
    files:
      - LICENSE.md
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^examples:'
      - '^ui:'
